# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b264e081bf285c45ae81029a14f8aa8ca9e0e6d1fe15fb4674e42f37a0d400624e2ab33316137a88987bd90265f834e39f544e19a8daba4e37cea35186244f

test:
  secret_key_base: 176edda3d5b6595d5b12766dfe96fe2309195624c794b6f0cffd41fd2f346166d49b0ac6999423a64b343eaa2414e6d360603c3f54ccc7ed21379dc45d0f20b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
